name: Update Exchange Rates

on:
  schedule:
    - cron: "0 1 * * *"  
  workflow_dispatch:       # 支持手动触发

jobs:
  fetch-rates:
    runs-on: ubuntu-latest
    steps:
      - name: 检出代码
        uses: actions/checkout@v3

      - name: 设置Python环境
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: 安装依赖
        run: pip install requests

      - name: 运行脚本
        env:
          EXCHANGE_RATE_API_KEY: ${{ secrets.EXCHANGE_RATE_API_KEY }}
        run: python fetch_rates.py
        
      - name: 提交更改
        run: |
          git config --global user.name "FireStar0507"
          git config --global user.email "18064625480@163.com"
          git add *
          git commit -m "自动更新汇率数据"
          # 使用GITHUB_TOKEN推送
          git push "https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
